name: Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@master
        with:
          platforms: "linux/amd64, darwin/amd64, windows/amd64"
          package: ""
          name: "ready"
          compress: "false"
          dest: "dist"
      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"
  publish:
    name: Publish package to Go proxy
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Get git tag
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Publish package
        run: GOPROXY=proxy.golang.org go list -m github.com/lewislbr/ready@"$GIT_TAG"
